#!/usr/bin/python

# Input: path files generated by CBS
# Output: Solution quality - Makespan and Sum of Cost

import re
import sys

for i in range(1, len(sys.argv), 1):
    makespan = 0
    soc = 0
    with open(sys.argv[i]) as f:
        lines = f.readlines()
        for line in lines:
            num_steps = len(re.findall(r'(\d+,\d+)', line)) - 1
            if makespan < num_steps:
                makespan = num_steps
            soc += num_steps

    print(sys.argv[i])
    print(f"Makespan : {makespan}")
    print(f"SoC      : {soc}")
    print()
